swagger: '2.0'
info:
  description: A API for the part managment tool Part-DB
  version: 1.0.0
  title: Part-DB API
  # put the contact info for your development or API team
  contact:
    name: Part-DB
    url: https://github.com/jbtronics/Part-DB

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: Part
  description: Part operations
- name: Category
  description: Category operations
- name: System
  description: System operations

paths:
  /system/info:
    get:
      tags:
      - System
      summary: Get informations about the system
      description: |
        Gets different informations like the version of Part-DB.
      produces:
      - "application/json"
      responses:
        "200":
          description: Informations about the system
          schema:
            $ref: '#/definitions/SystemInfo'
              
  /part/{pid}:
    get:
      tags:
        - Part
      summary: Gets all informations about the part with the given id
      produces:
        - application/json
      parameters: 
        - name: "pid"
          in: "path"
          description: "The id of the part which is requested"
          required: true
          type: number
          format: uint64
      responses:
        200:
          description: "Request was successful"
          schema:
            $ref: '#/definitions/Part'
        404:
          description: "No part with the given id, were found"
            
    delete:
      tags:
        - Part
      summary: Delets the given part
      produces:
         - application/json
      parameters:
        - name: "pid"
          in: "path"
          description: "The id of the part which is requested"
          required: true
          type: number
          format: uint64
      responses:
        200:
          description: "Part was successful deleted."
        404:
          description: "No part with the given id, were found"
          
    post:
      tags:
        - Part
      summary: Edits the values of the part.
      produces: 
        - application/json
      parameters: 
        - name: "pid"
          in: "path"
          description: "The id of the part which is requested"
          required: true
          type: number
          format: uint64
        - name : "new_vals"
          description: "The new data of the part. Only the values which should be changed"
          in: body
          schema:
            $ref: '#/definitions/Part'
      responses:
        200:
          description: "Part was successful edited."
        404:
          description: "No part with the given id, were found."
            
      
  /category/{cid}:
    get:
      tags:
        - Category
      summary: Gets all information about the category with the given id
      produces:
        - application/json
      parameters:
        - name: "cid"
          in: "path"
          description: "The id of the category requested."
          required: true
          type: number
          format: uint64
      responses:
        200:
          description: Request was successful
          schema:
            $ref: '#/definitions/Category'
        
          
definitions:
  SystemInfo:
    type: object
    required: 
    - Version
    properties:
      Version:
        type: string
        example: "V4.0 RC1"
      GitBranch:
        type: string
        example: "nextgen"
      GitCommit:
        type: string
        example: "fe1d67d"
        
  Part:
    type: object
    required: 
    - pid
    properties:
      pid:
        description: The id which identifies the part.
        type: number
        example: 10
      name:
        description: The name of the part.
        type: string
        example: "BC547"
      description:
        description: "The description of the part, with BBCode parsing"
        type: string
        example: "<b>NPN</b> Transistor"
      description_raw:
        description: "The description of the part, without BBCode parsing"
        type: string
        example: "[b]NPN[/b] Transistor"
      comment:
        description: "The comment of the part, with BBCode parsing."
        type: string
        example: "<i>Good</i> for NF."
      comment_raw:
        description: "The comment of the part, without BBCode parsing."
        type: string
        example: "[i]Good[/i] for NF."
      instock:
        description: The number of parts, which are currently in stock.
        type: number
        example: 3
      mininstock:
        type: number
        example: 3
      category:
        $ref: '#/definitions/Category'
      obsolete:
        description: "Check if the part is obsolete in all Suppliers"
        type: boolean
        example: true
      visible:
        description: "Check if the part is visible"
        type: boolean
        example: true
      orderdetails:
        type: array
        items:
          $ref: '#/definitions/OrderDetails'
      orderquantity:
        description: "The amount of parts, which should be ordered."
        type: number
        example: 0
      minorderquantity:
        description: "The minimum quantity, which should be ordered."
        type: number
        example: 10
      manualorder:
        description: "True, if the part were marked manually for ordering."
        type: boolean
        example: true
      lastmodified:
        description: "The datetime, when the part was last modified."
        type: string
        example: "2017-08-14 18:10:28"
      datetime_added:
        description: "The datetime, when the part was created."
        type: string
        example: "2015-05-17 11:45:06"
      footprint:
        $ref: '#/definitions/Footprint'
      storelocation:
        $ref: '#/definitions/StoreLocation'
      manufacturer:
        $ref: '#/definitions/Company'
      avgprice:
        description: "Returns the average price."
        type: number
        example: 3.2
      properties:
        type: array
        items:
          $ref: '#/definitions/PartProperty'
        
      
  Category:
    type: object
    required:
      - cid
    properties:
      cid:
        description: "The id of thecategory."
        type: number
        example: 23
      name:
        description: "The Name of the category."
        type: number
        example: "NPN"
      fullpath:
        description: "The Fullpath to the category."
        type: string
        example: "Transistors/NPN"
      parentid:
        description: The id of the parent category.
        type: number
        example: 3
      disable_footprints:
        description: "True, if footprints should be disabled for this category."
        type: boolean
        example: false
      disable_manufacturers:
        description: "True, if manufacturers should be disabled for this category."
        type: boolean
        example: true
      disable_autodatasheets:
        description: "True, if automatic autodatasheets should be disabled for this category."
        type: boolean
        example: false
      disable_properties:
        description: "True if automatic properties should be disabled."
        type: boolean
        example: false
      default_description:
        description: "The default desription for parts with this category."
        type: string
        example: "Test: ??"
      default_comment:
        description: "The default comment for part with this category."
        type: string
        example: "Test: ??"
  
  Attachement:
    type: object
    required:
      - aid
    properties:
      aid:
        description: "The id of the attachement."
        type: number
        example: 4
      name:
        description: "The name of the attachement."
        type: string
        example: "Attachement 1"
      isPicture:
        description: "True, if the Attachement has a picture extension."
        type: boolean
        example: true
      filename:
        description: "The filename of the attachement."
        type: string
        example: true
      showInTable:
        description: "True, if the attachement should be shown in the part tables."
        type: string
        example: "/data/bc547.pdf"
      "type":
        $ref: '#/definitions/AttachementType'
          
  AttachementType:
    type: object
    required:
      - atid
    properties:
      atid:
        description: "The id of the attachementtype."
        type: number
        example: 5
      name:
        description: "The name of the attachementtype"
        type: string
        example: "Pictures"
      fullpath:
        description: "The fullpath to the attachementtypes"
        type: string
        example: "Images / Pictures"
      parentid:
        description: "The id of the parent attachementtype"
        type: number
        example: 2
  
  Company:
    type: object
    required:
      - id
    properties:
      id:
        description: "The id of the Company"
        type: number
        example: 5
      name:
        description: "The name of the Company"
        type: string
        example: "ACME Inc."
      fullpath:
        description: "The fullpath to the Company"
        type: string
        example: "Mother Inc. / ACME Inc."
      parentid:
        description: "The id of the parent company"
        type: number
        example: 2
      address:
        description: "The address of the company"
        type: string
        example: "Example Street 4, 12345 Sampletown"
      phone_number:
        description: "The phone number of the company"
        type: string
        example: "(0123) 45678)"
      fax_number:
        description: "The fax number of the company"
        type: string
        example: "(0123) 45678)"
      website:
        description: "The website of the company"
        type: string
        example: "www.foo.bar"
      auto_url:
        description: "A url with the filed %PARTNR%, which can be used to generate a link to the part on the company website"
        type: string
        example: "www.foo.bar/%PARTNR%"
      
  OrderDetails:
    type: object
    required:
      - oid
    properties:
      oid:
        description: "The id of the OrderDetail"
        type: number
        example: 45
      supplier:
        $ref: '#/definitions/Company'
      supplierpartnr:
        description: "The Code, which identifies the part for the supplier."
        type: string
        example: "BC 547B"
      obsolete:
        description: "True, if the part is obsolete, which means it is no longer available"
        type: boolean
        example: false
      supplier_product_url:
        description: "The link to the website of the article on the suppliers website."
        type: string
        example: "https://foo.bar/BC547"
      pricedetails:
        type: array
        items:
          $ref: '#/definitions/PriceDetails'
  
  PriceDetails:
    type: object
    required: 
      - id
    properties:
      id:
        description: "The id of the PriceDetail"
        type: number
        example: 23
      quantity:
        description: "The related quantity for the PriceDetail"
        type: number
        example: 1
      price:
        description: "The price for this quantity as a float"
        type: number
        example: 0.27
      minDiscountQuantity:
        description: "Minimum discount quantity means the minimum order quantity for which the price of this orderdetails is valid."
        type: number
        example: 10
  
  StoreLocation:
    type: object
    required: 
      - lid
    properties:
      lid:
        description: "The id of the storelocation."
        type: number
        example: 4
      name:
        description: "The name of the storelocation."
        type: number
        example: "Location I-B4"
      fullpath:
        description: "The full path to the category."
        type: string
        example: "Location I / Location I-B4"
        
  PartProperty:
    type: object
    required: 
      - name
      - value
    properties:
      name:
        description: "The name field of the property, without a delimiter."
        type: string
        example: "max. Voltage"
      value:
        description: "The value field of the property."
        type: string
        example: "45V"
  
  Footprint:
    type: object
    required:
      - fid
    properties:
      fid:
        description: "The id of the footprint"
        type: string
        example: "DIP8"
      name:
        description: "The name of the footprint."
        type: string
        example: "DIP8"
      fullpath:
        description: "The fullpath to the footprint"
        type: string
        example: "DIP / DIP8"
      parentid:
        description: "The id of the parent"
        type: number
        example: 10
      filename:
        description: "Get the filename of the picture (absolute path from Part-DB root)"
        type: string
        example: "/img/DIP8.png"
      filename_valid:
        description: "Check if the filename is valid (picture exists)"
        type: boolean
        example: true
      filename3D:
        description: "Get the filename of the model (absolute path from Part-DB root)"
        type: string
        example: "/models/model.x3d"
      filename3D_valid:
        description: "Check if the filename is valid (model exists)."
        type: boolean
        example: true

# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /jbtronics/Part-DB/1.0.0
schemes:
 - https
 - http